import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CustomButton from '../components/CustomButton'
import CustomComp from '../components/CustomComp'
import Heading from '../components/Heading'
import HomePage from '../components/home'
import List from '../components/List'
import Text from '../components/polymorphic/Text.tsx/Text'
import Test from '../components/text'
import Toast from '../components/Toast'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePage name="md mohi" status="waiting" handleClick={(event, id) => { window.alert(`cliked ${event.clientX} ${id}`) }} style={ {padding:'1rem',background:'lightcyan',color:'black'}}/>
        <Heading>my heading</Heading>
        {/* <List items={["spiderman","batman","ironman","superman"]} onClick={(item)=>console.log(item)}/>
        <List items={[1,2,3]} onClick={(item)=>console.log(item)}/> */}
        <List items={[{ id: 'name',name:'md' }, { id: 'unknown' }]} onClick={(item) => console.log(item)} />
        <Test value={10} isPositive />
        <Toast position="left-top" />
        <CustomButton variant="primary" color="blue" onClick={() => { console.log('clicked') }} > click me </CustomButton>
        <Text size="lg" as="button"  color="primary">this is text</Text>
        <Text size="lg" as="h6" color="primary">this is text</Text>
        <CustomComp name="md" />
      </main>


    </div>
  )
}

export default Home
